'''You are given an array of integers temperatures where temperatures[i] represents the daily temperatures on the ith day.

Return an array result where result[i] is the number of days after the ith day before a warmer temperature appears on a future day. If there is no day in the future where a warmer temperature will appear for the ith day, set result[i] to 0 instead.

Example 1:

Input: temperatures = [30,38,30,36,35,40,28]

Output: [1,4,1,2,1,0,0]
Example 2:

Input: temperatures = [22,21,20]

Output: [0,0,0]
Constraints:

1 <= temperatures.length <= 1000.
1 <= temperatures[i] <= 100
'''
from typing import List
#brute force:
class Solution:
    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:
        n = len(temperatures) #we want to get the length of the temperatures list so that we can iterate through it and compare each temperature with the next temperatures to see if there is a warmer temperature in the future, since we want to return the number of days after the ith day before a warmer temperature appears on a future day, so we need to know how many temperatures there are in the list to be able to iterate through it and compare each temperature with the next temperatures to see if there is a warmer temperature in the future
        res = [] #we want to create an empty list to store the result of the number of days after the ith day before a warmer temperature appears on a future day, since we want to return this list at the end of the function, so we need to create an empty list to store the result before we start iterating through the temperatures list and comparing each temperature with the next temperatures to see if there is a warmer temperature in the future

        for i in range(n): #we want to iterate through the temperatures list using a for loop, since we want to compare each temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to use a for loop to iterate through the temperatures list and compare each temperature with the next temperatures to see if there is a warmer temperature in the future
            count = 1 #we want to initialize a count variable to 1, since we want to count the number of days after the ith day before a warmer temperature appears on a future day, so we need to initialize a count variable to 1 before we start comparing the current temperature with the next temperatures to see if there is a warmer temperature in the future, since we want to count the number of days after the ith day before a warmer temperature appears on a future day, so we need to initialize a count variable to 1 before we start comparing the current temperature with the next temperatures to see if there is a warmer temperature in the future
            j = i + 1 #we want to initialize a j variable to i + 1, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to initialize a j variable to i + 1 before we start comparing the current temperature with the next temperatures to see if there is a warmer temperature in the future, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to initialize a j variable to i + 1 before we start comparing the current temperature with the next temperatures to see if there is a warmer temperature in the future
            while j < n: #we want to use a while loop to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, since we want to keep comparing the current temperature with the next temperatures until we find a warmer temperature in the future or we reach the end of the temperatures list, so we need to use a while loop to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future
                if temperatures[j] > temperatures[i]: #if the next temperature is greater than the current temperature, it means that we have found a warmer temperature in the future, so we want to break out of the while loop and add the count variable to the result list, since we want to return the number of days after the ith day before a warmer temperature appears on a future day, so we need to add the count variable to the result list when we find a warmer temperature in the future
                    break
                j += 1#if the next temperature is not greater than the current temperature, it means that we have not found a warmer temperature in the future, so we want to increment the j variable to compare the current temperature with the next temperature in the temperatures list, since we want to keep comparing the current temperature with the next temperatures until we find a warmer temperature in the future or we reach the end of the temperatures list, so we need to increment the j variable to compare the current temperature with the next temperature in the temperatures list
                count += 1 #if the next temperature is not greater than the current temperature, it means that we have not found a warmer temperature in the future, so we want to increment the count variable to count the number of days after the ith day before a warmer temperature appears on a future day, since we want to return the number of days after the ith day before a warmer temperature appears on a future day, so we need to increment the count variable to count the number of days after the ith day before a warmer temperature appears on a future day, since we want to return the number of days after the ith day before a warmer temperature appears on a future day, so we need to increment the count variable to count the number of days after the
            count = 0 if j == n else count #if we have reached the end of the temperatures list and we have not found a warmer temperature in the future, it means that there is no day in the future where a warmer temperature will appear for the ith day, so we want to set the count variable to 0, since we want to return 0 if there is no day in the future where a warmer temperature will appear for the ith day, so we need to set the count variable to 0 if we have reached the end of the temperatures list and we have not found a warmer temperature in the future, since we want to return 0 if there is no day in the future where a warmer temperature
            res.append(count) #we want to append the count variable to the result list, since we want to return the number of days after the ith day before a warmer temperature appears on a future day, so we need to append the count variable to the result list after we have compared the current temperature with the next temperatures to see if there is a warmer temperature in the future, since we want to return the number of days after the ith day before a warmer temperature appears on a future day, so we need to append the count variable to the result list after we have compared the current temperature with the next temperatures to see if there is a warmer temperature in the future
        return res #we want to return the result list at the end of the function, since we want to return the number of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we need to return the result list at the end of the function, since we want to return the number of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we need to return the result list at the end of the function
    #time complexity: O(n^2) because we are using a nested loop to compare each temperature with the next temperatures to see if there is a warmer temperature in the future, so we are iterating through the temperatures list n times and for each temperature, we are iterating through the next temperatures in the temperatures list, which takes O(n) time, so the overall time complexity is O(n^2)
    #space complexity: O(n) because we are using a result list to store the number of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we are using O(n) space to store the result list
    #space complexity: O(1) because we are not using any additional space to store the result list, since we are using a variable to store the count of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we are using O(1) space to store the count variable, since we are not using any additional space to store the result list, since we are using a variable to store the count of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we are using O(1) space to store the count variable

#stack:
class Solution:
    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:
        res = [0] * len(temperatures) #we want to create a result list with the same length as the temperatures list and initialize it with 0, since we want to return the number of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we need to create a result list with the same length as the temperatures list and initialize it with 0, since we want to return 0 if there is no day in the future where a warmer temperature will appear for the ith day, so we need to initialize the result list with 0
        stack = [] #we want to use a stack to keep track of the indices of the temperatures in the temperatures list, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to use a stack to keep track of the indices of the temperatures in the temperatures list, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to use a stack to keep track of the indices of the temperatures in the temperatures list, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to use a stack to keep track of the indices of the temperatures in the temperatures list

        for i, t in enumerate(temperatures): #we want to iterate through the temperatures list using a for loop and get the index and the temperature at each index, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to use a for loop to iterate through the temperatures list and get the index and the temperature at each index, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to use a for loop to iterate through the temperatures list and get the index and the temperature at each index, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to use a for loop to iterate through the temperatures list and get the index and the temperature at each index
            while stack and t > stack[-1][0]: #we want to use a while loop to compare the current temperature with the last temperature in the stack, since we want to keep comparing the current temperature with the last temperature in the stack until we find a warmer temperature in the future or we reach the end of the stack, so we need to use a while loop to compare the current temperature with the last temperature in the stack, since we want to keep comparing the current temperature with the last temperature in the stack until we find a warmer temperature in the future or we reach the end of the stack, so we need to use a while loop to compare the current temperature with the last temperature in the stack, since we want to keep comparing the current temperature with the last temperature in the stack until we find a warmer temperature in the future or we reach the end of the stack, so we need to use a while loop to compare the current temperature with the last temperature in the stack, since we want to keep comparing the current temperature with the last temperature in the stack until we find a warmer temperature in the future or we reach the end of the stack
                stackT, stackInd = stack.pop() #we want to pop the last temperature and its index from the stack, since we want to compare the current temperature with the last temperature in the stack, so we need to pop the last temperature and its index from the stack, since we want to compare the current temperature with the last temperature in the stack, so we need to pop the last temperature and its index from the stack, since we want to compare the current temperature with the last temperature in the stack, so we need to pop the last temperature and its index from the stack, since we want to compare the current temperature with the last temperature in the stack, so we need to pop the last temperature and its index from the stack, since we want to compare the current temperature with the last temperature in the stack, so we need to pop the last temperature and its index from the stack
                res[stackInd] = i - stackInd #we want to set the result at the index of the last temperature in the stack to the difference between the current index and the index of the last temperature in the stack, since we want to return the number of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we need to set the result at the index of the last temperature in the stack to the difference between the current index and the index of the last temperature in the stack, since we want to return the number of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we need to set the result at the index of the last temperature in the stack to the difference between the current index and the index of the last temperature in the stack, since we want to return the number of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we need to set the result at the index of the last temperature in the stack to the difference between the current index and the index of the last temperature in the stack, since we want to return the number of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we need to set the result at the index of the last temperature in the stack to the difference between the current index and the index of the last temperature in the stack
            stack.append((t, i)) #we want to append the current temperature and its index to the stack, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to append the current temperature and its index to the stack, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to append the current temperature and its index to the stack, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to append the current temperature and its index to the stack, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to append the current temperature and its index to the stack, since we want to compare the current temperature with the next temperatures to see if there is a warmer temperature in the future, so we need to append the current temperature and its index to the stack
        return res #we want to return the result list at the end of the function, since we want to return the number of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we need to return the result list at the end of the function, since we want to return the number of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we need to return the result list at the end of the function
    #time complexity: O(n) because we are iterating through the temperatures list once and performing operations on the stack, which takes O(1) time, so the overall time complexity is O(n)
    #space complexity: O(n) because in the worst case, we could have all the temperatures in the stack if they are all in decreasing order, so we are using O(n) space to store the stack, since we are using a stack to keep track of the indices of

#dynamic programming:
class Solution:
    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:
        n = len(temperatures)
        res = [0] * n
        for i in range(n - 2, -1, -1):
            j = i + 1
            while j < n and temperatures[j] <= temperatures[i]:
                if res[j] > 0:
                    j += res[j]
                else:
                    j = n
            if j < n:
                res[i] = j - i
        return res
    #time complexity: O(n) because we are iterating through the temperatures list once and performing operations on the result list, which takes O(1) time, so the overall time complexity is O(n)
    #space complexity: O(n) because we are using a result list to store the number of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we are using O(n) space to store the result list
    #space complexity: O(1) because we are not using any additional space to store the result list, since we are using a variable to store the count of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we are using O(1) space to store the count variable, since we are not using any additional space to store the result list, since we are using a variable to store the count of days after the ith day before a warmer temperature appears on a future day for each temperature in the temperatures list, so we are using O(1) space to store the count variable